### ISSUE TITLE
Component placement

### ISSUE THREAD

**Issue by yanone** [noponies/sulphur-point#2]
This typeface lacks basic understanding of accent placement (especially in the Light master) and inconsistencies between masters. Please refine.
<img width="857" alt="Bildschirmfoto 2019-09-02 um 10 30 02" src="https://user-images.githubusercontent.com/175386/64100882-dc6ffe80-cd6c-11e9-88ac-3ca0772f1a9b.png">

**Comment by noponies** [comment]
@yanone You're right, they are all out.

Will get onto adjusting these.

**Comment by yanone** [comment]
Thanks. Please don't limit the adjustments to the shown glyphs. I picked these because they were obvious, but there could be more.

**Comment by noponies** [comment]
Yeah there are more. In some instances I've just messed it up and some like the Ų are me not refreshing the anchor locations in the affected components. The same mistake in say the ŗ is across all my typefaces. Good to get these fixed.

**Comment by noponies** [comment]
@yanone Have updated the component alignments and it should be good to go now.

<img width="828" alt="Screen Shot 2019-09-03 at 7 14 27 PM" src="https://user-images.githubusercontent.com/7235916/64151750-28ab6380-ce7f-11e9-99ab-8566c586a2a1.png">
